baseURL = "https://rayhanga.github.io/"
locale = "en-us"
title = "Rayhan Gusty Alif"
disableKinds = ["taxonomy", "term"]

[params]
  role = "SRE & DevOps Engineer"

[params.social]
  github = "https://github.com/rayhanga"
  linkedin = "https://linkedin.com/in/rayhanga"
  gitlab = "https://gitlab.com/rayhanga"
  twitter = "https://twitter.com/rayhanga"
  email = "mailto:rayhangustyalif@gmail.com"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10
  [menu.main.params]
    icon = "BasicUser24"

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 20
  [menu.main.params]
    icon = "BasicPencilEdit24"

[[menu.main]]
  name = "Projects"
  url = "/project/"
  weight = 30
  [menu.main.params]
    icon = "BasicCase24"

[taxonomies]
  tag = "tags"
