baseURL = "https://rayhanga.github.io/"
locale = "en-us"
title = "Rayhan Gusty Alif"
disableKinds = ["taxonomy", "term"]
theme = "minimalist-manifesto"

[build]
  writeStats = true

[params]
  role = "SRE & DevOps Engineer"
  cv = "https://docs.google.com/document/d/1cNftuhIEofydcsnAcCn2VYshLPSw6eBIsrS6pLq4s5E/edit?usp=sharing"

[params.social]
  github = "https://github.com/rayhanga"
  linkedin = "https://linkedin.com/in/rayhanga"
  gitlab = "https://gitlab.com/rayhanga"
  twitter = "https://twitter.com/rayhanga"
  email = "mailto:rayhangustyalif@gmail.com"

[[menu.main]]
  name = "About me"
  url = "/about/"
  weight = 10
  [menu.main.params]
    icon = "BasicUser24"

[[menu.main]]
  name = "My projects"
  url = "/project/"
  weight = 20
  [menu.main.params]
    icon = "BasicCase24"

[[menu.main]]
  name = "My blog"
  url = "/blog/"
  weight = 30
  [menu.main.params]
    icon = "BasicPencilEdit24"

[taxonomies]
  tag = "tags"
